name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Download dependencies
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Unit Test
      run: yarn test
